---
apiVersion: v1
kind: Pod
metadata:
  name: hostnetwork-demo
spec:
  hostNetwork: false
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: ["sh", "-c", "sleep 1h"]

# =============================== openai response  ===============================
# [
# {
#     "Rule": "Host Namespaces",
#     "Location": "spec.hostNetwork",
#     "Value": false,
#     "Message": "Sharing the host namespaces must be disallowed."
# }
# ]
# ================================================================================
---